version: 2

jobs:
  build:
    docker:
      # SEE https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11

    working_directory: /tmp/gostore

    environment:
      TEST_RESULTS: /tmp/test-results

    pre:

    steps:
      - run: go get github.com/mattn/goveralls

      - checkout
      - run: mkdir -p $TEST_RESULTS

      - run:
          name: Run unit tests
          command: go test -v -coverprofile=$TEST_RESULTS/coverage.out

      - run: goveralls -coverprofile=$TEST_RESULTS/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN