version: 2

jobs:
  build:
    docker:
      # SEE https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11

    working_directory: /tmp/gostore

    environment:
      TEST_RESULTS: /tmp/test-results

    pre:

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

        # restores saved cache if no changes are detected since last run
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys: [v1-pkg-cache]

      - run: go get github.com/mattn/goveralls
      - run: go get github.com/jstemmer/go-junit-report

      - run:
          name: Run unit tests
          command: go test -v -coverprofile=$TEST_RESULTS/coverage.out | tee $TEST_RESULTS/go-test.out

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - run: go-junit-report < $TEST_RESULTS/go-test.out > $TEST_RESULTS/go-test-report.xml
      - run: goveralls -coverprofile=$TEST_RESULTS/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: /tmp/test-results